# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/mysql:/var/run/mysqld
      - ./db/mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  app:
    build: .
    restart: always
    environment:
      DB_HOST: db
    ports:
      - 3001:3000
    depends_on:
      - db
    volumes: 
      - ./dev-env.json:/app/server/dist/config/env.json